image: node:16.14.0-alpine

stages:
  - build
  - test
  - register
  - deploy


cache:
  paths:
    - node_modules/

build:
  stage: build
  script:
    - yarn install
    - yarn run build
  artifacts:
    expire_in: 1 week
    paths:
      - dist

test:
  stage: test
  before_script:
    - apk update && apk add bash
    - apk add ca-certificates
    - wget -q -O /etc/apk/keys/sgerrand.rsa.pub https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub
    - wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.29-r0/glibc-2.29-r0.apk
    - apk add glibc-2.29-r0.apk
  script:
    - yarn install
    - yarn run test:unit
    - yarn run pact:publish

register:
  stage: register
  image: docker
  services:
    - docker:dind
  before_script:
    - docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_TOKEN
  script:
    - docker build -t "${DOCKER_HUB_USERNAME}/todo-ui:${CI_COMMIT_SHORT_SHA}" .
    - docker push "${DOCKER_HUB_USERNAME}/todo-ui:${CI_COMMIT_SHORT_SHA}"

deploy:
  stage: deploy
  image:
    name: alpine/helm:3.2.1
    entrypoint: [""]
  script:
    - echo ${KUBE_CONFIG} | base64 -d > config
    - export KUBECONFIG=config
    - helm repo add todo-app https://fnkaya.github.io/chart-museum/
    - helm repo update
    - helm upgrade --install todo-frontend todo-app/todo-frontend --version 0.1.0 --set image=fnkaya/todo-ui:${CI_COMMIT_SHORT_SHA} --set nodePort=30105  --namespace test

