apiVersion: v1
kind: Service
metadata:
  name: todo-backend-service
  labels:
    name: todo-backend-service
spec:
  type: NodePort
  selector:
    name: todo-backend-pod
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
      nodePort: {{ .Values.nodePort }}