apiVersion: v1
kind: Service
metadata:
  name: todo-frontend-service
  labels:
    name: todo-frontend-service
spec:
  type: NodePort
  selector:
    name: todo-frontend-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: {{ .Values.nodePort }}
